baseURL = 'https://joeygun.github.io/joeylai'
title = 'joey blog'
theme = 'paper'

[services]
  [services.disqus]
    shortname = 'hello'     # use disqus comments

[params]
  # color style
  color = 'wheat'                           # linen, wheat, gray, light

  # home page profile
  # avatar = 'lailinxiao@gmail.com'                 # gravatar email or image url
  # name = 'joey'
  # bio = ''


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages


